# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4BC6P7Sy9vrklOQt6h5IXnV0qsgYCTD
"""

import pandas as pd
data=[{"name":"alice","age":20,"grade":"A","mark":85},
      {"name":"bob","age":22,"grade":"B","mark":72},
      {"name":"charlie","age":19,"grade":"A","mark":92},
      {"name":"davied","age":21,"grade":"C","mark":65},
      {"name":"eva","age":20,"grade":"B","mark":74}]
df=pd.DataFrame(data)
print(df)

df

df.head(3)

df[['mark','name']]

df.loc[df['grade']=='A']