# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-gFOwIm3GbuL9GO-gES9DEAk0cNORKvC
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

df = pd.read_csv("student_performance_dataset.csv")


print("First 5 rows of the dataset:")
display(df.head())

print("\nDataset Info:")
df.info()


print("\nSummary Statistics:")
display(df.describe())

print("Missing values in each column:")
print(df.isnull().sum())

df = pd.get_dummies(df, drop_first=True)

df_subset = df.head(10)

plt.figure(figsize=(8,6))
plt.imshow(df_subset.corr(), cmap='coolwarm', interpolation='none')
plt.colorbar(label='Correlation')
plt.xticks(range(len(df.columns)), df.columns, rotation=90)
plt.yticks(range(len(df_subset.columns)), df_subset.columns)
plt.title("Correlation Heatmap (First 10 Rows Only)")
plt.show()

X = df.drop('Final_Exam_Score', axis=1)
y = df['Final_Exam_Score']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=29)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

model = LinearRegression()
model.fit(X_train, y_train)

print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)*100

print(f"Mean Squared Error (MSE): {mse}")
print(f"R-squared (R2): {r2}")