# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10GUjsEokYBKcPDdqeBc9nELfK2Y142wi
"""

import numpy as np

A = np.array([10, 20, 30, 40, 50])
B = np.array([5, 4, 3, 2, 1])

print("A + B =", A + B)
print("A - B =", A - B)
print("A * B =", A * B)
print("A / B =", A / B)

print("Mean of A =", np.mean(A))
print("Max of A =", np.max(A))
print("Min of A =", np.min(A))
print("Dot product (A·B) =", np.dot(A, B))


A_reshaped = A.reshape(5, 1)
print("Reshaped A (5x1):\n", A_reshaped)