# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13c7rYSVASPEuHeQRaeRn_hKIo-UPoZB-
"""

import matplotlib.pyplot as plt

days = ["Sunday","Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday" ]
temperatures = [44, 45, 40,42, 41, 40, 44]

plt.figure(figsize=(9,7))
plt.plot(days, temperatures, marker="o", linestyle="--", color="r")

plt.xlabel("Days of the Week")
plt.ylabel("Temperature (°C)")
plt.title("Temperature Variation Over a Week in Riyadh")

plt.show()